***This Basins Specification file (EXS) file has been generated from WinHSPF.
<WDMNAME><Ste><cSt><LatMin><LatMax><LngMin><LngMax><yyyymmdd><yyyymmdd>***
Snake410    1    1       0       0       0       0  2015 1 1  20161231
SIMQFLOWSUROIFOWAGWOSUPYPETXSAETUZSXLZSX     LOCATION***
 541   1 542 543 544 549 545 546 547 548  0  RCH54
***The following Storm dates are generated by subtracting the baseflow time series from the observed flow time series.
***The baseflow time series was generated using the HysepLocMin method that is available with the USGS Surface Water Toolbox.
***The storm date generation process is under development; users should verify these dates independently, and check for following issues.
***  1)	In some cases where two or three closely-spaced peaks should be considered as a single storm, the method divides them into separate storms.
***  2)	In some cases, the recession tails are too long. These storms should be shortened
*** 3)	Periods of prolonged runoff associated with spring snowmelt are included in the list of storms. These generally should be removed from the list.
<St>***
  10
 2015  5  7  0  0  0 2015  6  6  0  0  0
 2015  7  6  0  0  0 2015  7 12  0  0  0
 2015  7 13  0  0  0 2015  8  6  0  0  0
 2015 11 17  0  0  0 2015 12  7  0  0  0
 2016  3  8  0  0  0 2016  3 31  0  0  0
 2016  4 24  0  0  0 2016  5 23  0  0  0
 2016  7 10  0  0  0 2016  8  9  0  0  0
 2016  8 11  0  0  0 2016  8 19  0  0  0
 2016  8 31  0  0  0 2016  9 16  0  0  0
 2016 11 18  0  0  0 2016 12 25  0  0  0
*** This area was computed by WinHSPF as the total area of PERLNDs and IMPLNDs contributing to the calibration reach.
***It does Not include the area Of water bodies. It Is Not based On the published (e.g., USGS) streamgage drainage area.
<Area  >***
601931.4
   10.00     .03   10.00   15.00   15.00    2.50   20.00   15.00    1.50   30.00   15.00   20.00   15.00   10.00   10.00   15.00   20.00   15.00   15.00
***If you want to specify seasons for your Expert Statistics Calculation, specify them here.
***Seasons Is a keyword, that tells HSPEXP+ that user will provide it's own seasons
Seasons:
***Months selected for Summers, comma separated
6,7,8
***Months selected for Winters, comma separated
12,1,2
